# Generated by Django 4.0.3 on 2022-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('archivo', models.FileField(upload_to='archivos/documentos/')),
            ],
        ),
    ]
