# Generated by Django 4.0.3 on 2022-04-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='archivo',
            field=models.FileField(null='True', upload_to='archivos/documentos/'),
        ),
    ]
